-- pulseq initial schema. Generated by `prisma migrate dev --name init`.

CREATE TYPE "JobState" AS ENUM ('DELAYED', 'READY', 'LEASED', 'SUCCEEDED', 'FAILED', 'DEAD');

CREATE TABLE "jobs" (
    "id" UUID NOT NULL,
    "namespace" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "state" "JobState" NOT NULL DEFAULT 'READY',
    "attempt" INTEGER NOT NULL DEFAULT 0,
    "maxAttempts" INTEGER NOT NULL DEFAULT 5,
    "idempotencyKey" TEXT,
    "streamId" TEXT,
    "leaseOwner" TEXT,
    "leaseExpiresAt" TIMESTAMP(3),
    "runAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "enqueuedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "startedAt" TIMESTAMP(3),
    "finishedAt" TIMESTAMP(3),
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "lastError" TEXT,
    CONSTRAINT "jobs_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "jobs_namespace_state_idx" ON "jobs"("namespace", "state");
CREATE INDEX "jobs_namespace_runAt_idx" ON "jobs"("namespace", "runAt");
CREATE INDEX "jobs_idempotencyKey_idx" ON "jobs"("idempotencyKey");

CREATE TABLE "job_attempts" (
    "id" UUID NOT NULL,
    "jobId" UUID NOT NULL,
    "attempt" INTEGER NOT NULL,
    "worker" TEXT NOT NULL,
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finishedAt" TIMESTAMP(3),
    "outcome" TEXT NOT NULL,
    "error" TEXT,
    "durationMs" INTEGER,
    CONSTRAINT "job_attempts_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "job_attempts_jobId_idx" ON "job_attempts"("jobId");

CREATE TABLE "idempotency_keys" (
    "key" TEXT NOT NULL,
    "namespace" TEXT NOT NULL,
    "jobId" UUID NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'IN_PROGRESS',
    "resultHash" TEXT,
    "result" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completedAt" TIMESTAMP(3),
    "expiresAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "idempotency_keys_pkey" PRIMARY KEY ("key")
);
CREATE INDEX "idempotency_keys_namespace_idx" ON "idempotency_keys"("namespace");
CREATE INDEX "idempotency_keys_expiresAt_idx" ON "idempotency_keys"("expiresAt");

ALTER TABLE "job_attempts" ADD CONSTRAINT "job_attempts_jobId_fkey"
    FOREIGN KEY ("jobId") REFERENCES "jobs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
